config/routes.rb
Rails.application.routes.draw do
  root to: "app_home#index"

  get   "/sign-in",                     to: "sessions#new" ,                          as: :sign_in
  post  "/sign-in" ,                    to: "sessions#create"
  get   "/sign-out",                    to: "sessions#sign_out",                      as: :sign_out

  get   "/sign-up",                     to: "users#sign_up",                          as: :sign_up
  post  "/users",                       to: "users#create",                           as: :users

  get  "/assessment",                   to: "assessment#assessment_form" ,             as: :assessment_form
  post "/assessment/update_home",       to: "home_assessment#update_home",             as: :update_home
  post "/assessment/add_dependent",     to: "dependent_assessment#add_dependent",      as: :add_dependent
  delete "/assessment/remove_dependent/:id", to: "dependent_assessment#remove_dependent", as: :remove_dependent
  post "/assessment/add_contact",            to: "contact_assessment#add_contact",     as: :add_contact
  delete "/assessment/remove_contact/:id",   to: "contact_assessment#remove_contact",  as: :remove_contact
  post "/assessment/update_gear",      to: "gear_assessment#update_gear",              as: :update_gear

  get "/todo",                          to:"todo#index",                              as: :todo
  get "/todo/preps",                    to:"todo#preps",                              as: :preps
  get "/todo/preps/:id",                to:"todo#single_prep",                        as: :single_prep
  post "/todo/preps",                   to:"todo#update_prep",                         as: :update_prep
  delete "/todo/preps/:id",             to:"todo#delete_prep",                             as: :delete_prep
  get "todo/dash",                      to:"todo#dash",                               as: :dash

  get "/plan",                          to: "plan#index",                              as: :plan
end

app/views/refills/_hero.html.erb
<div class="hero">
  <div class="hero-inner">
    <% if !current_user %>
      <div class="hero-copy">
        <h1>Personalized Earthquake Preparation</h1>
        <p>Preparing for "The Big One" can be scary, time-consuming, and expensive.</p>
        <p>Ready.city helps you make a disaster preparation plan unique to your home, priorities and budget.</p>
      </div>
      <button id="sign-up"><%= link_to "Sign Up", sign_up_path %></button>
    <% else %>
      <div class="hero-copy">
        <% if @current_user.home_preparations.count == 0 %>
          <h1>Welcome to Ready.city!</h1>
          <h1>Let's get started.</h1>
        <% else %>
          <h1>Let's pick up where you left off.</h1>
        <% end %>
        <!-- <p> [progress indicator of assessment completion] </p> -->
        <p>
          <%= sprintf("%.2f", @todo.all_prep_progress)%> % of preparations complete
          (<%= @todo.completed_all_preps.to_i %> of <%= @todo.total_all_preps.to_i %>)
        </p>
      </div>
      <button> <%= link_to "Assessment", assessment_form_path %></button>
      <button> <%= link_to "Todo", todo_path %></button>
    <% end %>
  </div>
</div>

app/views/refills/_sign_in_popup.html.erb
<div class="modal">
  <label for="modal-1">
    <a class="modal-trigger">Sign In</a>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <h1>Sign In</h1>
      <div class="modal-close" for="modal-1"></div>
      <%= form_tag sign_in_path, :id => 'sign-in-form' do %>
        <div class="modal-content">
          <input type="email", name="email", placeholder="email">
          <input type="password", name="password", placeholder="password">
          <input type="submit", value="Sign In">
        </div>
      <% end %>
    </div>
  </div>
</div>