config/routes.rb
Rails.application.routes.draw do
  root to: "app_home#index"

  get   "/sign-in",                     to: "sessions#new" ,                          as: :sign_in
  post  "/sign-in" ,                    to: "sessions#create"
  get   "/sign-out",                    to: "sessions#sign_out",                      as: :sign_out

  get   "/sign-up",                     to: "users#sign_up",                          as: :sign_up
  post  "/users",                       to: "users#create",                           as: :users

  get  "/assessment",                   to: "assessment#assessment_form" ,             as: :assessment_form
  post "/assessment/update_home",       to: "home_assessment#update_home",             as: :update_home
  post "/assessment/add_dependent",     to: "dependent_assessment#add_dependent",      as: :add_dependent
  delete "/assessment/remove_dependent/:id", to: "dependent_assessment#remove_dependent", as: :remove_dependent
  post "/assessment/add_contact",            to: "contact_assessment#add_contact",     as: :add_contact
  delete "/assessment/remove_contact/:id",   to: "contact_assessment#remove_contact",  as: :remove_contact
  post "/assessment/update_gear",      to: "gear_assessment#update_gear",              as: :update_gear

  get "/todo",                          to:"todo#index",                              as: :todo
  get "/todo/preps",                    to:"todo#preps",                              as: :preps
  get "/todo/preps/:id",                to:"todo#single_prep",                        as: :single_prep
  post "/todo/preps",                   to:"todo#update_prep",                         as: :update_prep
  delete "/todo/preps/:id",             to:"todo#delete_prep",                             as: :delete_prep
  get "todo/dash",                      to:"todo#dash",                               as: :dash

  get "/plan",                          to: "plan#index",                              as: :plan
end

app/views/layouts/_contact_asmt_form.html.erb
<fieldset id="contact-field">
  <h2>Contacts</h2>
  <p class="form-descr">
    Add a friend or relative who lives outside the state who will be your means
    of communicating with other family members, both in and out of state, after
    an earthquake.
  </p>
  <ul id="contact-list">
    <% current_user.contacts.each do |c| %>
      <li class="asmt-list-item">
        <span><strong>Name:</strong> <%= c.name %></span>
        <button class="delete-record" href= "<%= remove_contact_path(c.id)%>"> x </button>
      </li>
    <% end %>
  </ul>
  <form action="/assessment/add_contact" method="post" class="asmt-form" id="contact-form">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>

    <div class="contact-block">
      <p class="form-field">
        <label for="text_field">Name</label>
        <input type="text" class="text_field" name="con_name">
      </p>
      <p class="form-field">
        <label for="text_field">Phone</label>
        <input type="text" class="text_field" name="con_phone">
      </p>
      <p class="form-field">
        <label for="text_field">email</label>
        <input type="text" class="text_field" name="con_email">
      </p>
    </div>
    <button id="submit-con">Add Contact</button>
  </form>
</fieldset>

app/views/layouts/_dep_asmt_form.html.erb
<fieldset id="dependent-field">
  <h2>Dependents</h2>
  <p class="form-descr">
    Add a record for each member of your household for whom you will be
    responsible during an emergency (including spouse/partner). Pets are
    also considered dependents and can be added with the 'Add Pet' button.
  </p>
  <ul id="dependent-list">
    <% current_user.dependents.each do |d| %>
      <li class="asmt-list-item">
        <span><strong>Name:</strong> <%= d.name %></span>
        <button class="delete-record" href= "<%= remove_dependent_path(d.id)%>"> x </button>
      </li>
    <% end %>
  </ul>
  <form action="/assessment/add_dependent" method="post" class="asmt-form" id="dependent-form">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <div class="form-field">
      <label for="text_field">Name</label>
      <input type="text" class="text_field" name="dep_name">
    </div>
    <div class="form-field" id="dep-type">
      <label for="dep_type">Human or Pet?</label>
      <label>
        <input type="radio" class="radio" name="human" value="true">
        Human
      </label>
      <label>
        <input type="radio" class="radio" name="human" value="false">
        Pet
      </label>
    </div>

    <input id="submit-dep" type="submit" value="Add and Save Dependent">
  </form>
</fieldset>

app/views/layouts/_gear_asmt_form.html.erb
<fieldset id="gear-field">
  <h2>Gear & Supplies</h2>
  <p class="form-descr">
    Here are a few of the most important pieces of gear to have ready in case of
    an emergency. It's OK if you don't have these items ready – just choose 'yes'
    or 'no' and click 'save gear' to generate a custom equipment list, which you
    can view on the 'todo' page.
  </p>
  <form action="/assessment/update_gear" method="post" class="asmt-form" id="gear-form">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <div class="gear-radio">
      <label for="gear_type">Flashlight</label>
      <h3>
        A flashlight with full batteries is near your bed, in case an earthquake
        strikes at night.
      </h3>
      <label>
        <input type="radio" class="radio" name="preparations[<%= @flashlight_prep.id %>][completed]" value="true" <%= 'checked' if @flashlight_prep.completed %>>
        Yes
      </label>
      <label>
        <input type="radio" class="radio" name="preparations[<%= @flashlight_prep.id %>][completed]" value="false" <%= 'checked' unless @flashlight_prep.completed %>>
        No
      </label>
    </div>
    <div class="gear-radio">
      <label for="gear_type">Clothes & Shoes</label>
      <h3>
        A full set of clothes (including a hat and jacket if needed in your local
        climate) and a set of sturdy shoes are by your bed, in case an earthquake
        strikes at night.
      </h3>
      <label>
        <input type="radio" class="radio" name="preparations[<%= @clothes_prep.id %>][completed]" value="true" <%= 'checked' if @clothes_prep.completed %>>
        Yes
      </label>
      <label>
        <input type="radio" class="radio" name="preparations[<%= @clothes_prep.id %>][completed]" value="false" <%= 'checked' unless @clothes_prep.completed %>>
        No
      </label>
    </div>
    <div class="gear-radio">
      <label for="gear_type">Pocket Radio</label>
      <h3>
        Most telephones will be out of order or used for emergency purposes, so
        a portable radios battery- or wind-up-powered radio citizens band (CB)
        or other two-way radio will be your best source of information.
      </h3>
      <label>
        <input type="radio" class="radio" name="preparations[<%= @pocket_radio_prep.id %>][completed]" value="true" <%= 'checked' if @pocket_radio_prep.completed %>>
        Yes
      </label>
      <label>
        <input type="radio" class="radio" name="preparations[<%= @pocket_radio_prep.id %>][completed]" value="false" <%= 'checked' unless @pocket_radio_prep.completed %>>
        No
      </label>
    </div>
    <input id="submit-gear" type="submit" value="Save Gear">
    <div class="success-message-gear">Gear Details Updated</div>
  </form>
</fieldset>

app/views/layouts/_header.html.erb
<div class="<%= @landing ? 'landing-header header-wrap' : 'header-wrap' %>">
  <header class="navigation navigation-wrapper">
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <%= link_to root_path do %>
      <div class="brand">
        <i class="fa fa-life-ring fa-4 logo-icon"></i>
        <span class="brand-name">Ready.city</span>
      </div>
    <% end %>
    <ul id="js-navigation-menu" class="navigation-menu show">
      <% if current_user %>
        <li class="nav-link"> Hello, <strong><%= current_user.username%></strong></li>
        <li class="nav-link"><%= link_to "Assessment", assessment_form_path %></li>
        <li class="nav-link"><%= link_to "To-Do List", todo_path %></li>
        <li class="nav-link"><%= link_to "Plan", plan_path %></li>
        <li class="nav-link"><%= link_to "Sign Out", sign_out_path %></li>
      <% else %>
        <li class="nav-link"><%= link_to "Sign Up", sign_up_path %></li>
        <li class="nav-link"><%= render "refills/sign_in_popup" %></li>
      <% end %>
    </ul>
  </header>
</div>

app/views/layouts/_home_asmt_form.html.erb
<fieldset id="home-field">
  <h2>Home</h2>
  <form action="/assessment/update_home" method="post" class="asmt-form" id="home-form">
  <p class="form-descr">
    Enter details about your home.
  </p>

    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>

    <p>
      <label for="text_field">Street Address</label>
      <input type="text" class="text_field" name="street_address" value="<%= @home.street_address %>">
    </p>
    <p>
      <label for="text_field">City</label>
      <input type="text" class="text_field" name="city" value="<%= @home.city %>">
    </p>
    <p>
      <label for="text_field">State</label>
      <input type="text" class="text_field" name="state" value="<%= @home.state %>">
    </p>
    <p>
      <label for="text_field">Zip</label>
      <input type="text" class="text_field" name="zip" value="<%= @home.zip %>">
    </p>

    <p>
      <label for="home_type">House or Apartment?</label>
      <label>
        <input type="radio" class="radio" name="home_type" value="house" <%= 'checked' if @home.is_house %>>
        House
      </label>
    </p>
    <p>
      <label>
        <input type="radio" class="radio" name="home_type" value="apartment" <%= 'checked' unless @home.is_house %>>
        Apartment
      </label>
    </p>

    <p>
      <label for="floor_dropdown">Number of Floors (including basement):</label>
      <select name="floor_count" value="<%= @home.structure["floors"] %>">
        <option value="1" <%='selected' if @home.structure["floors"] == 1 %>>1</option>
        <option value="2" <%='selected' if @home.structure["floors"] == 2 %>>2</option>
        <option value="3" <%='selected' if @home.structure["floors"] == 3 %>>3</option>
        <option value="4" <%='selected' if @home.structure["floors"] == 4 %>>4</option>
      </select>
    </p>

    <p>
      <label for="year_built">Year Built</label>
      <input type="text" class="text_field" name="year_built" value="<%= @home.structure["year_built"] %>">
    </p>

    <input type="submit" value="Save Home">
    <div class="success-message-home">Home Details Updated</div>
  </form>
</fieldset>

app/views/layouts/_landing_cards.html.erb
<div class="card" id="assess-card">
  <div class="card-image"></div>
  <div class="card-header">
    <h4>Assess</h4>
  </div>
  <div class="card-copy">
    <p>Your life is unique, and your disaster preparedness plan should reflect that. Complete a simple assessment of your home, emergency gear, dependents and contacts.</p>
  </div>
</div>

<div class="card" id="prepare-card">
  <div class="card-image"></div>
  <div class="card-header">
    <h4>Prepare</h4>
  </div>
  <div class="card-copy">
    <p>From the assessment, Ready.city generates a customized to-do list of preparations. Progress toward 100% readiness increases as you complete tasks.</p>
  </div>
</div>

<div class="card" id="react-card">
  <div class="card-image"></div>
  <div class="card-header">
    <h4>React</h4>
  </div>
  <div class="card-copy">
    <p>If a natural disaster strikes, you're going to want an action plan. As you finish preparation tasks, your plan is updated with reminders about how to stay safe, where to go, and who to contact.</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Earthquake Prep</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Hind+Siliguri:400,300' rel='stylesheet' type='text/css'>  </head>
  <body>
    <div class="<%= @landing ? 'landing' : '' %>"></div>
    <%= render "layouts/header" %>
    <div class="main">
      <% if flash %>
        <% flash.each do |key, value| %>
          <div class="flash-message flash-<%= key %>"><%= value %></div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>